---
title: "Data analysis"
author: "Tobias Gerstenberg"
date: "June 10, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load required packages 

```{r packages, eval=FALSE}
library(lsr)
library(psych) #useful functions
library(stats) #useful functions
library(afex) #mixed ANOVAS
library(MASS) #ordinal logistic regression
library(rms) #ordinal logistic regression #2
library(ggplot2) #plotting
library(xtable) #exporting tables into latex
library(lmtest) #likelihood ratio test
library(scales) #rescaling
library(lme4) #mixed effects model

library(mclust) #clustering

library(DAAG) #cross validation
library(boot) #boostrapping

library(stringr) #deal with strings
library(dplyr) #data frame manipulations
library(tidyr) #data restructuring

```

## Read data file 

```{r read_data, eval=F}
rm(list=ls())
df.data = read.csv("https://github.com/tobiasgerstenberg/expectation_responsibility/tree/master/data/data.csv",header=T,stringsAsFactors=F)
```

## Structure data 

```{r structure_data, eval=F}
goalie_spinner_situations = c("wrong_20","wrong_80",
                      "correct_80","correct_20",
                      "wrong_40","wrong_60",
                      "correct_40","correct_60",
                      "wrong_20","wrong_40",
                      "correct_40","correct_20",
                      "wrong_60","wrong_80",
                      "correct_80","correct_60")

situation_labels = paste0(rep(c("wrong_","correct_"),each=4), seq(20,80,20))

situation_labels2 = paste0(
  rep(c("negative_","positive_"),each=4),
  rep(rep(c("suboptimal_","optimal_"),each=2),2),
  rep(c("nonpivotal","pivotal"),2))

agent_labels = c("bad_agent","average_agent","good_agent")

#GOALIE EXPERIMENT

df.goalie_original = df.data %>%
  filter(experiment == "goalie_original") %>%
  mutate(data_tmp = data %>% strsplit('\n') %>% unlist %>% strsplit(','),
         extra_tmp = extra %>% strsplit('\n') %>% unlist %>% strsplit(','))

df.goalie_original.wide = matrix(unlist(df.goalie_original$data_tmp),nrow=nrow(df.goalie_original),byrow=T) %>%
  as.data.frame(stringsAsFactors=F) %>%
  mutate_each(funs(as.numeric)) %>%
  setNames(paste0(c("round_","ratingLeft_","ratingRight_","time_"),rep(1:8,each=4)))

df.goalie_original.long = df.goalie_original.wide %>%
  mutate(id = 1:nrow(.)) %>%
  wideToLong %>%
  select(-within,-time) %>%
  mutate(round = round + 1) %>%
  gather(key = situation, value = rating,c(ratingLeft,ratingRight)) %>%
  arrange(id,round,situation) %>%
  mutate(situation = rep(goalie_spinner_situations,length(unique(id))),
         situation = factor(situation,levels = situation_labels),
         outcome = str_extract_all(situation,c("wrong|correct"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("20|40|60|80"),simplify=T) %>% as.vector) %>%
  select(id,round,situation,outcome,probability,rating)


#SPINNER EXPERIMENT

df.spinner_original = df.data %>%
  filter(experiment == "spinner_original") %>%
  mutate(data_tmp = data %>% strsplit('\n') %>% unlist %>% strsplit(','),
         extra_tmp = extra %>% strsplit('\n') %>% unlist %>% strsplit(','))

df.spinner_original.wide = matrix(unlist(df.spinner_original$data_tmp),nrow=nrow(df.spinner_original),byrow=T) %>%
  as.data.frame(stringsAsFactors=F) %>%
  mutate_each(funs(as.numeric)) %>%
  setNames(paste0(c("round_","ratingLeft_","ratingRight_","time_"),rep(1:8,each=4)))

df.spinner_original.long = df.spinner_original.wide %>%
  mutate(id = 1:nrow(.)) %>%
  wideToLong %>%
  select(-within,-time) %>%
  mutate(round = round + 1) %>%
  gather(key = situation, value = rating,c(ratingLeft,ratingRight)) %>%
  arrange(id,round,situation) %>%
  mutate(situation = rep(goalie_spinner_situations,length(unique(id))),
         situation = factor(situation,levels = paste0(rep(c("wrong_","correct_"),each=4), seq(20,80,20))),
         outcome = str_extract_all(situation,c("wrong|correct"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("20|40|60|80"),simplify=T) %>% as.vector) %>%
  select(id,round,situation,outcome,probability,rating)

# GOALIE AGENTS EXPERIMENT

df.goalie_skill = df.data %>%
  filter(experiment == "goalie_skill") %>%
  mutate(data = str_replace_all(data,"penalty_miss","wrong"),
         data = str_replace_all(data,"penalty_save","correct"),
         data = str_replace_all(data,"bad goalkeeper","bad_agent"),
         data = str_replace_all(data,"average goalkeeper","average_agent"),
         data = str_replace_all(data,"skilled goalkeeper","good_agent")) %>%
  mutate(data_tmp = data %>% strsplit('\n') %>% unlist %>% strsplit(','),
         extra_tmp = extra %>% strsplit('\n') %>% unlist %>% strsplit(','))

df.goalie_skill.wide = matrix(unlist(df.goalie_skill$data_tmp),nrow=nrow(df.goalie_skill),byrow=T) %>%
  as.data.frame(stringsAsFactors=F) %>%
  setNames(c(paste(c("judgmentRound_","situationLeft_","ratingLeft_","situationRight_","ratingRight_","time_"),rep(1:8,each=6),sep=""),
             paste(c("inferenceRound_","agentTop_","ratingTop_","agentMiddle_","ratingMiddle_","agentBottom_","ratingBottom_"),rep(1:8,each=7),sep="")))

df.goalie_skill.long = df.goalie_skill.wide %>%
  mutate(id = 1:nrow(.)) %>%
  wideToLong() %>%
  select(-within) %>%
  mutate_each(funs(as.numeric),contains("rating"),judgmentRound) %>%
  mutate(judgmentRound = judgmentRound + 1) %>%
  arrange(id,judgmentRound)

# responsibility judgments
df.goalie_skill.long.responsibility = df.goalie_skill.long %>%
  select(id,judgmentRound,situationLeft,ratingLeft,situationRight,ratingRight) %>%
  gather(key = situation, value = rating,c(ratingLeft,ratingRight)) %>%
  select(-situationLeft,-situationRight) %>%
  rename(round = judgmentRound) %>%
  arrange(id,round,situation) %>%
  mutate(situation = rep(goalie_spinner_situations,length(unique(id))),
         situation = factor(situation,levels = situation_labels),
         outcome = str_extract_all(situation,c("wrong|correct"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("20|40|60|80"),simplify=T) %>% as.vector) %>%
  select(id,round,situation,outcome,probability,rating)

# agent inferences
df.goalie_skill.long.inference = df.goalie_skill.long %>%
  select(id,inferenceRound,contains("Top"),contains("Middle"),contains("Bottom")) %>%
  rename(agent_1 = agentTop, agent_2 = agentMiddle, agent_3 = agentBottom,
         rating_1 = ratingTop, rating_2 = ratingMiddle, rating_3 = ratingBottom,
         situation = inferenceRound) %>%
  wideToLong() %>%
  select(-within) %>%
  mutate(situation = factor(situation,levels = situation_labels),
         agent = factor(agent,levels = agent_labels),
         outcome = str_extract_all(situation,c("wrong|correct"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("20|40|60|80"),simplify=T) %>% as.vector) %>%
  arrange(id,situation,agent) %>%
  select(id,situation,outcome,probability,agent,rating)

# SPINNER AGENTS EXPERIMENT

df.spinner_skill = df.data %>%
  filter(experiment == "spinner_skill") %>%
  mutate(data = str_replace_all(data,"prediction_wrong","wrong"),
         data = str_replace_all(data,"prediction_correct","correct"),
         data = str_replace_all(data,"bad player","bad_agent"),
         data = str_replace_all(data,"average player","average_agent"),
         data = str_replace_all(data,"skilled player","good_agent")) %>%
  mutate(data_tmp = data %>% strsplit('\n') %>% unlist %>% strsplit(','),
         extra_tmp = extra %>% strsplit('\n') %>% unlist %>% strsplit(','))

df.spinner_skill.wide = matrix(unlist(df.spinner_skill$data_tmp),nrow=nrow(df.spinner_skill),byrow=T) %>%
  as.data.frame(stringsAsFactors=F) %>%
  setNames(c(paste(c("judgmentRound_","situationLeft_","ratingLeft_","situationRight_","ratingRight_","time_"),rep(1:8,each=6),sep=""),
             paste(c("inferenceRound_","agentTop_","ratingTop_","agentMiddle_","ratingMiddle_","agentBottom_","ratingBottom_"),rep(1:8,each=7),sep="")))

df.spinner_skill.long = df.spinner_skill.wide %>%
  mutate(id = 1:nrow(.)) %>%
  wideToLong() %>%
  select(-within) %>%
  mutate_each(funs(as.numeric),contains("rating"),judgmentRound) %>%
  mutate(judgmentRound = judgmentRound + 1) %>%
  arrange(id,judgmentRound)

# responsibility judgments
df.spinner_skill.long.responsibility = df.spinner_skill.long %>%
  select(id,judgmentRound,situationLeft,ratingLeft,situationRight,ratingRight) %>%
  gather(key = situation, value = rating,c(ratingLeft,ratingRight)) %>%
  select(-situationLeft,-situationRight) %>%
  rename(round = judgmentRound) %>%
  arrange(id,round,situation) %>%
  mutate(situation = rep(goalie_spinner_situations,length(unique(id))),
         situation = factor(situation,levels = situation_labels),
         outcome = str_extract_all(situation,c("wrong|correct"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("20|40|60|80"),simplify=T) %>% as.vector) %>%
  select(id,round,situation,outcome,probability,rating)

# agent inferences
df.spinner_skill.long.inference = df.spinner_skill.long %>%
  select(id,inferenceRound,contains("Top"),contains("Middle"),contains("Bottom")) %>%
  rename(agent_1 = agentTop, agent_2 = agentMiddle, agent_3 = agentBottom,
         rating_1 = ratingTop, rating_2 = ratingMiddle, rating_3 = ratingBottom,
         situation = inferenceRound) %>%
  wideToLong() %>%
  select(-within) %>%
  mutate(situation = factor(situation,levels = situation_labels),
         agent = factor(agent,levels = agent_labels),
         outcome = str_extract_all(situation,c("wrong|correct"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("20|40|60|80"),simplify=T) %>% as.vector) %>%
  arrange(id,situation,agent) %>%
  select(id,situation,outcome,probability,agent,rating)

# MANAGER AGENTS EXPERIMENT

df.manager_skill = df.data %>%
  filter(experiment == "manager_skill") %>%
  mutate(data = str_replace_all(data,"bad manager","bad_agent"),
         data = str_replace_all(data,"average manager","average_agent"),
         data = str_replace_all(data,"skilled manager","good_agent")) %>%
  mutate(data_tmp = data %>% strsplit('\n') %>% unlist %>% strsplit(','),
         extra_tmp = extra %>% strsplit('\n') %>% unlist %>% strsplit(','))

df.manager_skill.wide = matrix(unlist(df.manager_skill$data_tmp),nrow=nrow(df.manager_skill),byrow=T) %>%
  as.data.frame(stringsAsFactors=F) %>%
  select(-1) %>%
  setNames(c(
    paste(c("situation_","rating_"),rep(1:8,each=2),sep=""),
    paste(c("inferenceRound_","agentTop_","ratingTop_","agentMiddle_","ratingMiddle_","agentBottom_","ratingBottom_"),rep(1:8,each=7),sep="")))


df.manager_skill.long = df.manager_skill.wide %>%
  mutate(id = 1:nrow(.)) %>%
  wideToLong() %>%
  select(-within) %>%
  mutate_each(funs(as.numeric),contains("rating")) %>%
  arrange(id)

# responsibility judgments
df.manager_skill.long.responsibility = df.manager_skill.long %>%
  select(id,situation,rating) %>%
  mutate(situation = factor(situation,levels = situation_labels2),
         outcome = str_extract_all(situation,c("negative|positive"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("suboptimal|optimal"),simplify=T) %>% as.vector,
         pivotality = str_extract_all(situation,c("nonpivotal|pivotal"),simplify=T) %>% as.vector) %>%
  select(id,situation,outcome,probability,pivotality,rating)

# agent inferences
df.manager_skill.long.inference = df.manager_skill.long %>%
  select(id,inferenceRound,contains("Top"),contains("Middle"),contains("Bottom")) %>%
  rename(situation = inferenceRound) %>%
  rename(agent_1 = agentTop, agent_2 = agentMiddle, agent_3 = agentBottom,
         rating_1 = ratingTop, rating_2 = ratingMiddle, rating_3 = ratingBottom) %>%
  wideToLong() %>%
  select(-within) %>%
  mutate(situation = factor(situation,levels = situation_labels2),
         agent = factor(agent,levels = agent_labels),
         outcome = str_extract_all(situation,c("negative|positive"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("suboptimal|optimal"),simplify=T) %>% as.vector,
         pivotality = str_extract_all(situation,c("nonpivotal|pivotal"),simplify=T) %>% as.vector) %>%
  arrange(id,situation,outcome,probability,pivotality,agent,rating) %>%
  select(id,situation,outcome,probability,pivotality,agent,rating)

# GARDENER AGENTS EXPERIMENT

df.gardener_skill = df.data %>%
  filter(experiment == "gardener_skill") %>%
  mutate(data = str_replace_all(data,"bad gardener","bad_agent"),
         data = str_replace_all(data,"average gardener","average_agent"),
         data = str_replace_all(data,"skilled gardener","good_agent")) %>%
  mutate(data_tmp = data %>% strsplit('\n') %>% unlist %>% strsplit(','),
         extra_tmp = extra %>% strsplit('\n') %>% unlist %>% strsplit(','))

df.gardener_skill.wide = matrix(unlist(df.gardener_skill$data_tmp),nrow=nrow(df.gardener_skill),byrow=T) %>%
  as.data.frame(stringsAsFactors=F) %>%
  select(-1) %>%
  setNames(c(
    paste(c("situation_","rating_"),rep(1:8,each=2),sep=""),
    paste(c("inferenceRound_","agentTop_","ratingTop_","agentMiddle_","ratingMiddle_","agentBottom_","ratingBottom_"),rep(1:8,each=7),sep="")))

df.gardener_skill.long = df.gardener_skill.wide %>%
  mutate(id = 1:nrow(.)) %>%
  wideToLong() %>%
  # select(-within) %>%
  mutate_each(funs(as.numeric),contains("rating")) %>%
  arrange(id)

# responsibility judgments
df.gardener_skill.long.responsibility = df.gardener_skill.long %>%
  select(id,situation,rating) %>%
  mutate(situation = factor(situation,levels = situation_labels2),
         outcome = str_extract_all(situation,c("negative|positive"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("suboptimal|optimal"),simplify=T) %>% as.vector,
         pivotality = str_extract_all(situation,c("nonpivotal|pivotal"),simplify=T) %>% as.vector) %>%
  select(id,situation,outcome,probability,pivotality,rating)

# agent inferences
df.gardener_skill.long.inference = df.gardener_skill.long %>%
  select(id,inferenceRound,contains("Top"),contains("Middle"),contains("Bottom")) %>%
  rename(situation = inferenceRound) %>%
  rename(agent_1 = agentTop, agent_2 = agentMiddle, agent_3 = agentBottom,
         rating_1 = ratingTop, rating_2 = ratingMiddle, rating_3 = ratingBottom) %>%
  wideToLong() %>%
  select(-within) %>%
  mutate(situation = factor(situation,levels = situation_labels2),
         agent = factor(agent,levels = agent_labels),
         outcome = str_extract_all(situation,c("negative|positive"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("suboptimal|optimal"),simplify=T) %>% as.vector,
         pivotality = str_extract_all(situation,c("nonpivotal|pivotal"),simplify=T) %>% as.vector) %>%
  arrange(id,situation,outcome,probability,pivotality,agent,rating) %>%
  select(id,situation,outcome,probability,pivotality,agent,rating)


# GARDENER NO SKILL

df.gardener_noskill = df.data %>%
  filter(experiment == "gardener_noskill") %>%
  mutate(data = str_replace_all(data,"bad gardener","bad_agent"),
         data = str_replace_all(data,"average gardener","average_agent"),
         data = str_replace_all(data,"skilled gardener","good_agent")) %>%
  mutate(data_tmp = data %>% strsplit('\n') %>% unlist %>% strsplit(','),
         extra_tmp = extra %>% strsplit('\n') %>% unlist %>% strsplit(','))

df.gardener_noskill.wide = matrix(unlist(df.gardener_noskill$data_tmp),nrow=nrow(df.gardener_noskill),byrow=T) %>%
  as.data.frame(stringsAsFactors=F) %>%
  select(-1) %>%
  setNames(paste0(c("situation_","rating_"),rep(1:12,each=2)))

df.gardener_noskill.long = df.gardener_noskill.wide %>%
  mutate(id = 1:nrow(.)) %>%
  wideToLong() %>%
  select(-within) %>%
  mutate(situation = factor(situation,levels = c(situation_labels2,"negative_chance_nonpivotal",
                                                 "negative_chance_pivotal","positive_chance_nonpivotal",
                                                 "positive_chance_pivotal")),
         outcome = str_extract_all(situation,c("negative|positive"),simplify=T) %>% as.vector,
         probability = str_extract_all(situation,c("suboptimal|optimal|chance"),simplify=T) %>% as.vector,
         pivotality = str_extract_all(situation,c("nonpivotal|pivotal"),simplify=T) %>% as.vector,
         rating = as.numeric(rating)) %>%
  arrange(id,situation,outcome,probability,pivotality,rating) %>%
  select(id,situation,outcome,probability,pivotality,rating)

# save data frames in lists

responsibility.list = list(goalie_original = df.goalie_original.long,
                       spinner_original = df.spinner_original.long,
                       goalie = df.goalie_skill.long.responsibility,
                       spinner = df.spinner_skill.long.responsibility,
                       manager = df.manager_skill.long.responsibility,
                       gardener = df.gardener_skill.long.responsibility,
                       gardener_noskill = df.gardener_noskill.long)

inference.list = list(goalie = df.goalie_skill.long.inference,
                   spinner = df.spinner_skill.long.inference,
                   manager = df.manager_skill.long.inference,
                   gardener = df.gardener_skill.long.inference)

# remove unnecessary variables
rm(list = setdiff(ls(),c("df.data","responsibility.list","inference.list")))
```


